version: "3.7"

services:
  user_db:
    container_name: user_db
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5
    networks:
    -  red-users
  users:
    container_name: users
    build:
      context: ./
      dockerfile: ./users/Dockerfile
    ports:
      - 3000:3000
    environment:
      DB_USER: postgres
      DB_PASSWORD: 123456
      DB_HOST: user_db
      DB_PORT: 5432
      DB_NAME: user_db
    depends_on:
      user_db:
        condition: service_healthy
    networks:
      - red-users
networks:
  red-users:
   driver: bridge