name: Test coverage
on:
  workflow_dispatch:
jobs:
  test_user:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123456
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    strategy:
      matrix:
        python-version: ["3.10"]
    env:
      DB_USER: postgres
      DB_PASSWORD: 123456
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: user_db
    steps:
      - name: checkout de repositorio
        uses: actions/checkout@v4
      - name: configuracion de entorno de python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run unit tests
        run: pytest --cov=users -v -s --cov-fail-under=70    
